# Exported from Render on 2024-10-11T21:55:02Z
services:
- type: web
  name: iac-demo
  runtime: python
  repo: https://github.com/SaulVVelazquez/iac-demo
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python3 app.py
version: "1"
